### ISSUE TITLE
Initial to-do's

### ISSUE THREAD

**Issue by 0xCoto** [0xCoto/NetworkOptimizer#1]
- [ ] Create axvline on Motor Iterations to pinpoint optimal (best) configuration so far
- [ ] Maybe partially extend Position vs Iteration line by a dashed line (indicating where it's currently heading)?
- [ ] Contour linewidth should be ~halved?
- [ ] Make fullscreen togglable in GUI & CLI
- [ ] Exit fullscreen/end program when optimization is complete/close GUI when optimization starts
